# Generated by Django 5.2.1 on 2025-06-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_squad_home_venue"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tournament",
            table="tournament",
        ),
    ]
